spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login-page?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: kalswl99
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-ddl: true

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8282

jwt:
  header: authorization
  secret: bXktcHJvamVjdC1uYW1lLWlzLWp3dC1sb2dpbi1wYWdlLWFuZC10aGlzLWlzLW15LWp3dC1zZWNyZXQK
  #'my-project-name-is-jwt-login-page-and-this-is-my-jwt-secret' 을 base64로 인코딩한 값
  token-validity: 10800